<?php
/**
 * 分组详情
 * Date: 2018/10/4
 * Time: 9:18
 */
namespace App\Http\Admin\Actions\System\Group;

use Admin\Actions\BaseAction;

class DetailAction extends BaseAction
{
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
    }
}