<?php
/**
 * 分组列表
 * Date: 2018/10/4
 * Time: 9:17
 */
namespace App\Http\Admin\Actions\System\Group;

use Admin\Actions\BaseAction;

class IndexAction extends BaseAction
{
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
    }
}