<?php
/**
 * 师生交互
 * Date: 2018/10/29
 * Time: 23:19
 */
namespace App\Http\Front\Actions\Interact\Admonition;

use Front\Actions\BaseAction;

class IndexAction extends BaseAction
{
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
    }
}