<?php
/**
 * 投票问题列表
 * Date: 2018/10/20
 * Time: 22:34
 */
namespace App\Http\Admin\Actions\Activity\Poll\Question;

use Admin\Actions\BaseAction;

class IndexAction extends BaseAction
{
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
    }
}