<?php
/**
 * 权限列表
 * Date: 2018/10/3
 * Time: 20:05
 */
namespace App\Http\Admin\Actions\System\Authority;

use Admin\Actions\BaseAction;

class IndexAction extends BaseAction
{
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
    }
}