<?php
/**
 * 网络投票活动列表
 * Date: 2018/10/20
 * Time: 22:14
 */
namespace App\Http\Admin\Actions\Activity\Poll;

use Admin\Actions\BaseAction;

class IndexAction extends BaseAction
{
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
    }
}