<?php
/**
 * 教研活动列表
 * Date: 2018/10/30
 * Time: 0:01
 */
namespace App\Http\Front\Actions\Article\Teching;

use Front\Actions\BaseAction;

class IndexAction extends BaseAction
{
    /**
     *
     */
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
    }
}