<?php
/**
 * 用户权限
 * Date: 2018/10/6
 * Time: 0:47
 */
namespace App\Http\Admin\Actions\Master;

use Admin\Actions\BaseAction;

class AuthorityAction extends BaseAction
{
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
    }
}