<?php
/**
 * 用户详情
 * Date: 2018/10/6
 * Time: 0:27
 */
namespace App\Http\Admin\Actions\Master;

use Admin\Actions\BaseAction;

class DetailAction extends BaseAction
{
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
    }
}