<?php
/**
 * 教研活动详情
 * Date: 2018/10/20
 * Time: 1:14
 */
namespace App\Http\Admin\Actions\Article\Teching;

use Admin\Actions\BaseAction;
use Admin\Traits\ApiActionTrait;

class InfoAction extends BaseAction
{
    use ApiActionTrait;

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
    }
}