<?php
/**
 * 文章缓存刷新
 * Date: 2018/10/23
 * Time: 21:36
 */
namespace App\Http\Admin\Actions\Article\Operate;

use Admin\Actions\BaseAction;

class FreshAction extends BaseAction
{
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
    }
}
