<?php
/**
 * demo回调
 * Date: 2018/10/26
 * Time: 12:30
 */
namespace App\Http\Web\Actions\Wechat\Demo;

use Front\Actions\BaseAction;

class OauthAction extends BaseAction
{
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
    }
}
