<?php
/**
 * 学区详情
 * Date: 2018/10/7
 * Time: 10:58
 */
namespace App\Http\Admin\Actions\School\District;

use Admin\Actions\BaseAction;

class DetailAction extends BaseAction
{
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
    }
}