<?php
/**
 * 学区列表
 * Date: 2018/10/7
 * Time: 10:57
 */
namespace App\Http\Admin\Actions\School\District;

use Admin\Actions\BaseAction;

class IndexAction extends BaseAction
{
    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
    }
}