<?php
/**
 * 教育快讯列表
 * Date: 2018/10/30
 * Time: 0:05
 */
namespace App\Http\Front\Actions\Article\Exam;

use Front\Actions\BaseAction;
use Front\Traits\ArticleActionTrait;

class InfoAction extends BaseAction
{
    use ArticleActionTrait;

    public function run()
    {
        $this->initArticleByCode();
        parent::run(); // TODO: Change the autogenerated stub
    }
}